- package/package.json
- package/src/hydra-ai/ai-service.ts
- package/src/hydra-ai/hydra-ai-backend.ts
- package/src/hydra-ai/hydra-ai-client.ts
- package/src/hydra-ai/hydra-server-action.ts
Updates system prompt generation to allow user-injected custom system prompts, which is the initial text sent to the LLM to describe the AI's role.
Updates HydraClient constructor to allow for optional `systemInstructions` parameter.
If no custom systemInstructions are passed, the default (the instruction starting with "You are a UI/UX designer..." we've been using so far) is used automatically.
Also updates the structure of the `ai-service` slightly to make it more clear that we are generating 1. a system prompt and 2. a user or content prompt.
> Add system prompt customization

- package/package-lock.json
- package/package.json
- package/src/hydra-ai/context-utils.ts
- package/src/hydra-ai/hydra-ai-client.ts
AI should know about certain context with every single message. For example, the user's current time (and timezone) should always be known.
Adds a method that updates each user message and adds default context.
So far default context only includes user's current timestamp
> Add default timestamp context to every message

- package/package-lock.json
- package/package.json
- package/src/hydra-ai/ai-service.ts
At the final generation prompt, adds the component description to the prompt so the ai can take into account any user-defined instructions for how to fill the props of the chosen component.
Also reduces temperature of openai calls to improve consistency.
> Add component description to generation prompt

- package/src/hydra-ai/helper-components/hydra-chat/hydra-chat.tsx
> Suggestion to reduce bottom margin in chat window?

- package/package-lock.json
- package/package.json
- package/src/hydra-ai/hydra-ai-client.ts
- package/src/hydra-ai/hydra-server-action.ts
Adds a constructer param to HydraClient to allow the user to specify which openAI model should be used behind the scenes.
Defaults to 'gpt-4o'.
If the provided value is not a valid model name, the client app will throw an error on `generateComponent` request
> Allow openai model choice

- package/package-lock.json
- package/package.json
- package/src/hydra-ai/hydra-ai-client.ts
- package/src/hydra-ai/model/generate-component-response.ts
Adds an optional callback param to generateComponent that is called at different stages of component generation with a string describing the stage. 
- Currently the stage names are hardcoded, but in future we could allow configuration of what string is sent at each stage.
- We can update tool definitions to include a string that should be sent to the callback when that tool is being used, instead of "Getting additional data"
-  We can stream text back as it is received from OpenAI streaming request
> Initial progress updates callback

- package/package-lock.json
- package/package.json
- package/src/hydra-ai/ai-service.ts
- package/src/hydra-ai/model/component-metadata.ts
Allows tools to define parameters with enums, to make sure hydra calls functions with valid values for parameters that have a specific set of choices.
> Allow enum fields in tool parameters

- package/package-lock.json
- package/package.json
- package/src/hydra-ai/hydra-ai-client.ts
- package/src/hydra-ai/hydra-api/hydra-api-service.ts
- package/src/index.ts
Updates HydraClient to request generation and hydration from a "Hydra API" instead of from the NextJS server actions, for those who don't want to maintain their own "backend"
> Allow HydraClient to request HydraApi if key and url provided

- react-sdk/src/providers/tambo-provider.tsx
Changes the error throw to an error log since in NextJS the provider is rendered once on server-side.
> fix: Don't throw error if TamboProvider used outside browser

- react-sdk/src/providers/tambo-thread-provider.tsx
fixes some backwards compatibility with 0.19
> fix: make threadId optional in sendThreadMessage

- package-lock.json
- showcase/src/components/generative/GraphChatInterface.tsx
- showcase/src/components/ui/graph.tsx
Adds default values for showcase graph and pads data so nothing breaks while labels/data stream in.
Also updates registration useEffect so the graph doesn't re-register many times
> fix: add default value for showcase graph during streaming

- react-sdk/src/providers/__tests__/tambo-thread-provider.test.tsx
- react-sdk/src/providers/tambo-thread-provider.tsx
Now that toolcall requests can include a displaymessage, this PR updates the response handling flow so that it isn't overwritten by the following message from tambo.
> fix: Show toolcall message in thread

- package-lock.json
- react-sdk/package.json
- react-sdk/src/providers/__tests__/tambo-thread-provider.test.tsx
- react-sdk/src/providers/tambo-thread-provider.tsx
- react-sdk/src/util/registry.ts
Allows sending tools to tambo without associating them with components.
Enables client-side MCP usage
Currently still sends tools that are associated with a component within the component's definition, even though serverside the association is ignored and tools are all considered separately.
> feat: send all defined tools, even if they are not associated with a component

- README.md
> chore: fix toolSchema example in  README.md

- react-sdk/package.json
- react-sdk/src/hooks/use-thread-input.ts
- react-sdk/src/providers/tambo-thread-provider.tsx
Updates `submit` and `sendThreadMessage` to take a 'forceToolChoice` param where a tool name can be passed as a way to force it to be called before normal processing.
This is a way to tell tambo "Before processing the user message, call this tool to get extra information"
> feat: add forceToolChoice param

- cli/src/registry/message/message.tsx
- package-lock.json
- react-sdk/package.json
- react-sdk/src/providers/tambo-thread-provider.tsx
- react-sdk/src/util/tool-caller.ts
Updates react sdk to catch toolcall failures and send a description of the error back to tambo as the tool response, while also attaching the error to the message so we can handle displaying the failure.
Updates the Message registry component to show x if a toolcall fails instead of the checkmark
> feat: handle toolcall failures

- cli/src/registry/message/message.tsx
Updates the installable Message component to make the 'tool status' message clickable, which expands to show the tool name and parameters.
> feat: show toolcall name and params under status

- package-lock.json
- react-sdk/package.json
- react-sdk/src/providers/tambo-thread-provider.tsx
exposes   `updateThreadName: (name: string, threadId?: string) => void;` from useTamboThread
If no threadId is provided, uses the currentThread's id.
> feat: add method for changing a thread's name

- react-sdk/src/providers/tambo-thread-provider.tsx
previously information about a toolcallrequest (like the actionType field) was not added to the local thread message before running the toolcall. So we were not seeing the 'tool processing' ui until after the tool completed.
> fix: update local toolrequestmessage before running toolcall

- package-lock.json
- react-sdk/package.json
- react-sdk/src/providers/__tests__/tambo-thread-provider.test.tsx
- react-sdk/src/providers/tambo-thread-provider.tsx
updates react sdk to send toolcall counts during processing of a user message, so api can handle limiting based on project configuration
> fix: send toolcall counts

- react-sdk/src/index.ts
- react-sdk/src/providers/index.ts
- react-sdk/src/providers/tambo-prop-stream-provider.tsx
This PR fixes missing exports for the TamboPropStreamProvider and useTamboStream hook, and adds TypeScript exports for compound component prop types.
- Added exports for TamboPropStreamProvider and useTamboStream hook to make the stream provider publicly available
- Fixed JSDoc documentation to correctly reference streamKey parameter instead of key 
- Added TypeScript type exports for TamboPropStreamProviderProps, LoadingProps, EmptyProps, and CompleteProps to enable better type safety for consumers
None - this is purely additive and fixes missing exports
> fix: update exports for tambo stream provider

- docs/content/docs/meta.json
- docs/content/docs/tambo-mcp-server/index.mdx
- docs/content/docs/tambo-mcp-server/meta.json
adds a page with info for installing tambo's mcp server into IDEs
> docs: add tambo mcp doc page

- react-sdk/src/providers/hooks/__tests__/use-tambo-session-token.test.tsx
- react-sdk/src/providers/hooks/use-tambo-session-token.tsx
- react-sdk/src/providers/tambo-client-provider.tsx
- react-sdk/src/providers/tambo-provider.tsx
- react-sdk/src/providers/tambo-stubs.tsx
- react-sdk/src/providers/tambo-thread-input-provider.tsx
exposes an `isUpdating` field from `useTamboSessionToken`, and exposes the resulting value from client provider.
> feat: expose isUpdating from useTamboSessionToken

- react-sdk/src/context-helpers/__tests__/context-helpers-provider.test.tsx
- react-sdk/src/context-helpers/registry.ts
- react-sdk/src/providers/__tests__/tambo-context-helpers-provider.test.tsx
- react-sdk/src/providers/tambo-context-helpers-provider.tsx
doing global registration is an anti-pattern in react, and may break some apps, especially those that have multiple react roots
> feat(context-helpers): remove global context helper registry

- docs/content/docs/concepts/additional-context/index.mdx
- docs/content/docs/concepts/components/interactable-components.mdx
- react-sdk/src/context-helpers/current-interactables-context-helper.ts
- react-sdk/src/context-helpers/index.ts
- react-sdk/src/index.ts
- react-sdk/src/providers/__tests__/tambo-interactables-additional-context-edge-cases.test.tsx
- react-sdk/src/providers/__tests__/tambo-interactables-additional-context.test.tsx
- react-sdk/src/providers/tambo-interactable-provider.tsx
- **New context helper**: `currentInteractablesContextHelper` automatically registers when using `TamboInteractableProvider`
- **Simplified architecture**: Adapted to provider-only system (no global registry dependencies)
- **Complete API**: Includes disable, override, and customization options
- **Comprehensive tests**: 13 tests covering core functionality and edge cases
- **Integrated docs**: Added customization examples to existing interactable components page
Users can now ask "what's on the page?" and get comprehensive answers about their interactable components without any additional setup. The context
automatically includes component IDs, names, descriptions, current props, and schema information.
https://github.com/user-attachments/assets/9b84afac-1685-4cf8-9eb7-46dad34e775a
None …
> feat(interactables):   Add automatic context injection for interactable components that sends their current state to the AI by default.

- react-sdk/src/mcp/__tests__/tambo-mcp-provider.test.tsx
- react-sdk/src/mcp/tambo-mcp-provider.tsx
Updates our MCP tool call error handling to expect the `resonse` object to contain a `content` field that is an array of content part objects, rather than assuming it will be a string. Described here https://modelcontextprotocol.io/specification/2025-06-18/server/tools#error-handling
Avoids returning "Error: [object Object]" to tambo, which doesn't tell tambo anything about the error's reason.
> fix: Extract error messages from mcp tool response content array

- cli/package.json
- cli/src/registry/message/message.tsx
- docs/package.json
- docs/src/components/tambo/message.tsx
- package-lock.json
- react-sdk/package.json
- react-sdk/src/providers/__tests__/tambo-registry-provider.test.tsx
- react-sdk/src/providers/__tests__/tambo-thread-provider.test.tsx
- react-sdk/src/providers/tambo-provider.tsx
- react-sdk/src/providers/tambo-registry-provider.tsx
- react-sdk/src/providers/tambo-thread-provider.tsx
- react-sdk/src/util/tool-caller.ts
- showcase/package.json
- showcase/src/components/ui/message.tsx
This allows for having a handler when an unregistered tool is called
```ts
const handleTool = useCallback(async (toolName: string, args) => {
console.log("Found an unknown tool", toolName);
return "Nope!";
},[]);
...
return <TamboProvider tools={myTools} onCallUnknownTool={handleTool}>...</TamboProvider>;
```
- **add new onCallUnknownTool handler**
- **add docs**
> feat(sdk): Add onCallUnregisteredTool callback for handling unexpected tool callbacks

- react-sdk/src/mcp/__tests__/mcp-client.test.ts
- react-sdk/src/mcp/mcp-client.ts
This simply adds a reconnect() - it does not (yet) actually have an auto-reconnect or anything
> feat(mcp): Add reconnection logic + method to MCP Client

- .github/workflows/release-please.yml
this keeps us from building docs + showcase, just speeds up the publishing process by ~2-4 mins
> chore(publish): Only build publishable packages on release

- cli/src/registry/thread-history/thread-history.tsx
- showcase/src/components/ui/thread-history.tsx
- This PR fixes the sidebar animation of the thread-history component when collapsing and expanding. The sidebar now opens smoothly without text wrapping issue.
- Improved animation transitions for sidebar collapse/expand
- Fixed buggy feel while opening the sidebar
-Before
https://github.com/user-attachments/assets/611423c1-18d5-44f5-812c-b3b762446331
-After
https://github.com/user-attachments/assets/98f8c2d3-91d9-41d9-9fcc-2767b4ed6627
https://github.com/user-attachments/assets/027829dd-7cbc-40be-805d-1aa9f4a574a4
---
###Note
-First-time contributing to tambo, please let me know if I've missed any guidelines...happy to make adjustments.
> fix(thread-history): improve sidebar animation smoothness

- react-sdk/src/mcp/__tests__/mcp-client.test.ts
- react-sdk/src/mcp/mcp-client.ts
- react-sdk/src/mcp/tambo-mcp-provider.tsx
mainly this just stores the session id in the client so it works across reconnects
this was brought over by hand from https://github.com/tambo-ai/tambo-cloud/pull/1858
> feat(mcp): add very early session support

- showcase/src/components/sidebar-link.tsx
- showcase/src/components/sidebar.tsx
- This PR highlights the current component in the sidebar to improve navigation ux.
- Added showcase/src/components/sidebar-link.tsx (client) to compute active state via usepathname and style the active link.
- Updated showcase/src/components/sidebar.tsx (server) to render SidebarLink.
- Before
https://github.com/user-attachments/assets/8012f1dc-e6a5-428b-ba69-1b235e9278bb
- After
https://github.com/user-attachments/assets/85f1b511-e2c4-49db-b799-13541b6aab72
---
###vNote
- please let me know if I've missed any guidelines...happy to make adjustments. 
ps: feel free to close the pr if this is not needed. :)
> feat(sidebar): highlight active link

- react-sdk/src/providers/__tests__/tambo-thread-provider.test.tsx
- react-sdk/src/providers/tambo-thread-provider.tsx
I'm deprecating this from the API, and making the api always return "internal" messages (which don't really have any meaning now)
> chore(api): remove includeInternal - we always pass true anyway
