tambo-ai/tambo

demo/weather-app-demo/README.md, demo/weather-app-demo/src/app/components/rain-chart.tsx, demo/weather-app-demo/src/app/dynamic-chatbox/dynamic-chatbox.tsx, demo/weather-app-demo/src/app/dynamic-chatbox/info.tsx, demo/weather-app-demo/src/app/helpers.ts, demo/weather-app-demo/src/app/services/hydra.ts
adds changes that were made in forked repo for weather app demo
=> Update with fork weather demo changes

demo/frontend-hydra-demo/package-lock.json, demo/frontend-hydra-demo/package.json, demo/weather-app-demo/package-lock.json, demo/weather-app-demo/package.json, package/package.json, package/src/hydra-ai/ai-service.ts, package/src/hydra-ai/hydra-ai.ts
adds a parameter to hydra constructor to choose openai model
=> allow openai model choice

package/README.md, package/package.json
updates package readme after restructure
=> Update package readme

package/README.md, package/package.json, package/src/hydra-ai/hydra-ai-client.ts, package/src/hydra-ai/model/component-metadata.ts
Allows the getComponentContext prop to take an async function, since most data fetching functions will be.
=> allow async component context function

package/package.json, package/src/hydra-ai/helper-components/hydra-chat/hydra-chat-message.ts, package/src/hydra-ai/helper-components/hydra-chat/hydra-chat.tsx, package/src/hydra-ai/helper-components/hydra-chat/hydra-message-history.tsx, package/src/hydra-ai/helper-components/hydra-chat/index.ts, package/src/hydra-ai/helper-components/hydra-chat/send-icon.tsx, package/src/hydra-ai/helper-components/hydra-chat/spoke-spinner.tsx, package/src/hydra-ai/model/index.ts, package/src/index.ts
Adds a new HydraChat component to the npm package so users don't have to handle making a "dynamic component chatbox" themselves.
=> Add chat component to package

package/package.json, package/src/hydra-ai/ai-service.ts, package/src/hydra-ai/helper-components/hydra-chat/hydra-chat.tsx, package/src/hydra-ai/hydra-ai-client.ts, package/src/hydra-ai/model/component-choice.ts, package/src/hydra-ai/model/generate-component-response.ts
Allows hydra to return a string message to be shown alongside the returned component
=> Include text response

package/.env.example, package/.gitignore, package/drizzle.config.js, package/migrations/0000_create_components_table.sql, package/migrations/meta/0000_snapshot.json, package/migrations/meta/_journal.json, package/package-lock.json, package/package.json, package/src/db/schema.ts, package/src/hydra-ai/ai-service.ts, package/src/hydra-ai/helper-components/hydra-chat/hydra-chat.tsx, package/src/hydra-ai/hydra-ai-backend.ts, package/src/hydra-ai/hydra-ai-client.ts, package/src/hydra-ai/hydra-server-action.ts, package/src/hydra-ai/model/component-choice.ts, package/src/hydra-ai/model/component-metadata.ts, package/src/hydra-ai/model/input-context.ts, package/src/index.ts, package/tsconfig.json
This pr adds set up for a postgres DB to store registered components. 
I also change the prompting strategy to only provide relevant context and allow AI to send text msgs.
I've made changes to hydra client and backend structure to facilitate these updates. Please comment any questions that you have.
=> set up DB infra and prompting

package/package.json, package/src/hydra-ai/hydra-ai-backend.ts, package/src/hydra-ai/hydra-server-action.ts
Makes pg db optional for now, since it's not used yet.
=> make db optional

package/package.json, package/src/hydra-ai/ai-service.ts, package/src/hydra-ai/model/component-metadata.ts
Updates component context tool type and mapping function to allow array params in tools.
=> allow array types in params of defined context tools

README.md, package/README.md, package/docs/context-tools.md, package/package-lock.json, package/package.json, package/tsconfig.json
Updates README and /package/README to show instructions for registering components with descriptions and context tool definitions.
=> Update README documentation to include instructions for context tool definitions 

package/README.md, package/src/hydra-ai/hydra-ai-client.ts, package/src/hydra-ai/hydra-api/hydra-api-service.ts
Adds a HydraClient options object so only desired options need to be set.
Also adds default url for HydraApi.
=> add clientoptions and default api url

hydra-client/package.json, hydra-client/src/hydra-ai/hydra-ai-client.ts, hydra-client/src/hydra-ai/model/component-choice.ts, hydra-client/src/hydra-ai/model/generate-component-response.ts
updates dto types to include suggested actions passed from server
=> Allow suggested actions

hydra-client/src/hydra-ai/hydra-api/hydra-api-service.ts, hydra-client/src/hydra-ai/model/component-choice.ts
- **include thread id in request, if sent**
- **include threadid in hydrate too**
=> Allow inclusion of threadId

hydra-client/package-lock.json, hydra-client/package.json, hydra-client/src/hydra-ai/hydra-ai-client.ts
- **retain and propagate thread id**
- **bump version**
=> Retain and propagate threadId

hydra-client/package.json, hydra-client/src/hydra-ai/hydra-ai-client.ts
- **make sure to return the threadId to the caller**
- **version bump**
=> Make api response include threadId

hydra-client/package-lock.json, hydra-client/package.json, hydra-client/src/hydra-ai/model/component-metadata.ts, hydra-client/src/hydra-ai/model/generate-component-response.ts
- **actually add the threadId to the definition**
- **make @types/json-schema a peer**
- **version bump**
=> Add threadId, JSONSchema

react/src/hooks/use-thread-input.ts
allows the input hook to use streaming
=> chore: add param for streamResponse to input hook's submit

.vscode/extensions.json, .vscode/settings.json, release-please-config.json
- **chore: use node-workspace to catch inter dependencies**
- **chore: add default vscode stuff for consistency**
=> chore: a few other devex things: default formatting, recommended plugins'

.gitignore, package-lock.json, showcase/eslint.config.mjs, showcase/package.json, showcase/src/components/ui/graph.tsx, showcase/tsconfig.json, turbo.json
- **let NODE_ENV through turbo**
- **simplier than reduce**
- **let showcase use shared config**
- **ignore more**
- **working shared eslint config**
=> chore: let showcase have shared eslint config

react/package.json
this is mostly just to trigger a release
=> fix: repo url with "npm pkg fix"

.github/workflows/release-please.yml, package-lock.json, react-sdk/README.md, react-sdk/package.json
- **try renaming react-sdk itself**
- **actions too**
=> fix: renaming react suffix on package (as a test)

.github/workflows/release-please.yml, package-lock.json, react-sdk/README.md, react-sdk/package.json
Didn't work
Reverts tambo-ai/tambo#114
=> revert: "fix: renaming react suffix on package (as a test)"

package-lock.json, react-sdk/package.json, react-sdk/src/hooks/use-component-state.tsx, react-sdk/src/providers/tambo-thread-provider.tsx
- **bump the typescript-sdk**
- **add now-required componentState**
- **fix lint**
=> feat: bump typescript-sdk and fix react hooks lint

cli/package.json, cli/src/cli.ts, package-lock.json
- **fix: check versions**
- **use semver for version check for local development**
- **handle unrecognized commands**
=> fix: warn users if they are using old tambo cli

package-lock.json, react-sdk/src/providers/tambo-provider.tsx
- **remove hack**
- **require new ts sdk**
=> fix: force typescript-sdk to be the right version

.github/workflows/ci.yml, package-lock.json, react-sdk/jest.config.ts, react-sdk/package.json, react-sdk/src/hooks/__tests__/use-suggestions.test.tsx
- **add prettier-2 for inline snapshots**
- **add prettier-2 for inline snapshots**
- **fix suggestions tests**
- **add tests to CI**
=> test: enable tests in builds, fix suggestions test

package-lock.json, react-sdk/jest.config.ts, react-sdk/package.json, react-sdk/src/hooks/__tests__/use-suggestions.test.tsx, react-sdk/src/hooks/__tests__/use-tambo-threads.test.tsx, react-sdk/src/hooks/react-query-hooks.ts, react-sdk/src/hooks/use-suggestions.ts, react-sdk/src/hooks/use-tambo-threads.ts, react-sdk/src/providers/tambo-provider.tsx, react-sdk/src/setupTests.ts, react-sdk/src/testing/types.ts
- **add options to we can cancel retries in tests**
- **initial jest setup**
- **tests for useThreadList**
- **remove duplicate hook**
- **coerce a few tests to the right types**
- **fix a few more types**
=> test: start wiring up hook tests

cli/src/registry/message-input/message-input.tsx
Updates style of installable message-input component
=> feat(cli): update message-input component style

.github/dependabot.yml
update groups: eslint, radix-ui
=> chore: update dependabot groups

react-sdk/src/providers/tambo-provider.tsx, react-sdk/src/providers/tambo-registry-provider.tsx
- **add tool registry prop**
- **oops, use array one**
=> fix: Add `tools=` prop to register tools in provider

react-sdk/src/hooks/use-suggestions.ts, react-sdk/src/providers/tambo-thread-provider.tsx
- **no longer used**
- **update to use proper role**
- **add some awaits, not quite working**
- **make sure to add the *new* message before the update**
- **simplify update**
=> fix: make sure to show each streamed message, even if new ones come in on the same stream

package-lock.json, react-sdk/package.json, react-sdk/src/index.ts, react-sdk/src/model/component-metadata.ts, react-sdk/src/providers/tambo-mcp-provider.tsx, react-sdk/src/testing/tools.ts, react-sdk/src/util/mcp-client.ts, react-sdk/src/util/mcp-tools-client.ts, react-sdk/src/util/registry.ts
- **strawman mcp client**
- **let tools just have a raw JSONSchema**
- **add mcp provider, separate from other parts**
=> feat: add support for browser-visible MCP servers

cli/src/commands/create-app.ts, cli/src/commands/init.ts, create-tambo-app/src/index.ts
- **use the current directory name as the package name**
- **better adapt steps if in .**
- **npx -y**
- **add * as a mask so user sees input**
=> fix: small devex tweaks

cli/src/cli.ts, cli/src/commands/add/utils.ts, cli/src/commands/create-app.ts, cli/src/commands/list/index.ts
- **make sure not to blow up on non-components**
- **add a list command**
=> fix(cli): a few more dev tweaks to allow listing components, not crashing on add, etc

react-sdk/eslint.config.mjs, react-sdk/src/mcp/mcp-client.ts, react-sdk/src/providers/tambo-thread-provider.tsx
- **enforce rules of hooks so we stop breaking exhaustive deps**
- **jsdoc missing param**
- **fix deps**
- **options should be optional**
=> fix: make options optional in sendThreadMessage

cli/package.json, cli/src/registry/message/config.json, cli/src/registry/message/message.tsx, package-lock.json, showcase/package.json, showcase/src/components/ui/message.tsx
- **add @tambo-ai/typescript-sdk to showcase for types**
- **use whitespac-pre-wrap for tools**
=> fix: use proper whitespace wrapping and format tool params correctly

cli/src/cli.ts, cli/src/commands/add/index.ts, cli/src/commands/add/utils.ts, cli/src/commands/list/index.ts, cli/src/commands/update.ts, cli/src/commands/upgrade/components.ts
- **support mulitple components in add/update**
- **filter knownw components by whether they exist in the registry**
- **do not ask the user multiple times for src dir**
=> feat: allow multiple components to add / update command

package-lock.json, showcase/src/app/components/(blocks)/message-thread-collapsible/page.tsx, showcase/src/app/components/(blocks)/message-thread-full/page.tsx, showcase/src/app/components/(blocks)/message-thread-panel/page.tsx, showcase/src/app/components/(canvas)/canvas-space/page.tsx, showcase/src/app/components/(generative)/form/page.tsx, showcase/src/app/components/(generative)/graph/page.tsx, showcase/src/app/components/(message-primitives)/message-input/page.tsx, showcase/src/app/components/(message-primitives)/message/page.tsx, showcase/src/app/components/(message-primitives)/thread-content/page.tsx, showcase/src/app/components/(message-primitives)/thread-history/page.tsx, showcase/src/app/components/demo-wrapper.tsx, showcase/src/app/components/layout.tsx, showcase/src/app/get-started/page.tsx, showcase/src/components/generative/CanvasChatInterface.tsx, showcase/src/components/sidebar.tsx, showcase/src/components/ui/doc-components.tsx, showcase/src/components/ui/message.tsx, showcase/src/components/ui/syntax-highlighter.tsx, showcase/src/lib/navigation.ts
- **dedupe**
- **basic message primitives**
- **better document sub-components**
- **add syntax highlighting**
- **clean up unfinished states**
- **add installation instructions**
- **move install instructions up**
=> feat: document primitives, elevate install instructions

cli/src/registry/thread-history/thread-history.tsx
Updates thread-history component to add ui for renaming or 'ai generating' a name for a thread.
=> feat: add ui for thread renaming

cli/eslint.config.mjs, cli/src/cli.ts, cli/src/commands/init.ts, cli/src/commands/upgrade/utils.ts, cli/src/registry/message/message.tsx, cli/src/types/components.d.ts, cli/src/types/utils.d.ts, showcase/src/components/ui/message.tsx
- **support server-side tool calls in a hacky way**
- **re-enable any, and fix or disable where appropriate**
=> fix: show tool calls even if they're run on the server

cli/package.json, cli/src/registry/message/message.tsx, package-lock.json, react-sdk/package.json, showcase/package.json, showcase/src/components/ui/message.tsx
- **update to new typescript-sdk to pick up toolCallRequest location**
- **get rid of weird cast now that we have proper types**
=> fix: update typescript-sdk to get updated component decision type

cli/src/cli.ts, cli/src/commands/add/component.ts, cli/src/commands/add/index.ts, cli/src/commands/add/types.ts, cli/src/commands/add/utils.ts, cli/src/commands/init.ts, cli/src/commands/list/index.ts, cli/src/commands/update.ts, cli/src/commands/upgrade/components.ts, cli/src/commands/upgrade/index.ts
* --prefix adds directory prefix to replace components/ui or whatever
* -y answers yes to all confirmations
- **feat: add --prefix for add/update/list/etc**
- **add "-y" flag to answer yess to everythign**
=> feat: add -y and --prefix flags to cli

cli/package.json, package-lock.json, react-sdk/package.json, react-sdk/src/providers/tambo-client-provider.tsx, react-sdk/src/providers/tambo-provider.tsx, showcase/package.json
- **bump sdk to get bearer auth security**
- **add support for passing user token in**
- **properly send token with form-encoded value**
- **bump sdk again**
=> feat: support accessToken

package-lock.json, react-sdk/package.json
- **run npm install to sync up package-lock**
- **add ts-node as explicit dependency**
=> chore(deps): add back ts-node to make jest happy

docs/content/docs/concepts/components/interactable-components.mdx, docs/content/docs/concepts/components/meta.json
Adds a page describing "interactable components" and how to use `withTamboInteractable`
=> docs: Add Interactables doc page

docs/content/docs/meta.json, docs/content/docs/models/labels.mdx, docs/content/docs/models/meta.json, package-lock.json
- this section is mainly to add information about different labels that we have for different models in the LLM settings.
=> docs: add new section for Models

cli/package.json, cli/src/registry/map/map.tsx, package-lock.json, react-sdk/package.json, react-sdk/src/providers/tambo-thread-provider.tsx, showcase/package.json
- **bump to latest typescript-sdk**
- **stop using contextKey from return value**
=> feat(api): stop using contextKey returned from API

.github/dependabot.yml
- **chore: make a single fumadocs dependabot group**
- **also add next deps**
- **and tailwind**
=> chore(deps): add some dependabot groups for jest, tailwind, next

.gitignore, docs/src/app/(docs)/styles.css, docs/src/components/header-bar.tsx, package-lock.json
=> fix(docs): fixed document alignment issue

react-sdk/src/mcp/__tests__/use-mcp-servers.test.tsx, react-sdk/src/mcp/index.ts, react-sdk/src/mcp/tambo-mcp-provider.tsx
- **expose MCP client and its connection state**
- **add tests**
=> feat(mcp): Add hook to get at MCP servers for reconnection

AGENTS.md, CLAUDE.md, cli/AGENTS.md, cli/CLAUDE.md, create-tambo-app/AGENTS.md, create-tambo-app/CLAUDE.md, docs/AGENTS.md, docs/CLAUDE.md, react-sdk/AGENTS.md, react-sdk/CLAUDE.md, showcase/AGENTS.md, showcase/CLAUDE.md
- Added AGENTS.md
- Added CLAUDE.md pointers
=> chore: add agents.md & claude.md to monorepo.
